# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2a40660728de7a2a50ea759dd3dcf2b4ce752cd286c52e7ffafffb42f82ba95a0f2b0d5a4f36cbe868e7284823280e3caca2ff42dff159784a02f5c9a34986a

test:
  secret_key_base: 012dacaf69809bfe1e48379b4216f6858190ece054bdfa07b33fa35761baf3551d4c151eb8986116ec1b39e66e63f397082530d13447439b0cf5c82639556321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
